In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
df = pd.read_csv("/home/havin-benoy/Desktop/Pyspiders/ml/Assignments/Ice_cream selling data.csv")
df.head(5)

   Temperature (°C)  Ice Cream Sales (units)
0         -4.662263                41.842986
1         -4.316559                34.661120
2         -4.213985                39.383001
3         -3.949661                37.539845
4         -3.578554                32.284531

In [12]:
print(df.corr())

                         Temperature (°C)  Ice Cream Sales (units)
Temperature (°C)                 1.000000                -0.175184
Ice Cream Sales (units)         -0.175184                 1.000000

In [13]:
df2 = pd.read_csv("/home/havin-benoy/Desktop/Pyspiders/ml/Assignments/Student_Performance.csv")
df2

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [14]:
print(df2.corr(numeric_only=True))

                                  Hours Studied  Previous Scores  Sleep Hours  \
Hours Studied                          1.000000        -0.012390     0.001245
Previous Scores                       -0.012390         1.000000     0.005944
Sleep Hours                            0.001245         0.005944     1.000000
Sample Question Papers Practiced       0.017463         0.007888     0.003990
Performance Index                      0.373730         0.915189     0.048106

                                  Sample Question Papers Practiced  \
Hours Studied                                             0.017463
Previous Scores                                           0.007888
Sleep Hours                                               0.003990
Sample Question Papers Practiced                          1.000000
Performance Index                                         0.043268

                                  Performance Index
Hours Studied                              0.373730
Previous Scores                            0.915189
Sleep Hours                                0.048106
Sample Question Papers Practiced           0.043268
Performance Index                          1.000000