In [126]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, root_mean_squared_error,mean_squared_error

In [127]:
df = pd.read_csv("/home/havin-benoy/Desktop/Pyspiders/ml/Datasets/auto-mpg.csv")

display(df.head())

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [128]:
df["car name"].unique()

<StringArray>
[ 'chevrolet chevelle malibu',          'buick skylark 320',
         'plymouth satellite',              'amc rebel sst',
                'ford torino',           'ford galaxie 500',
           'chevrolet impala',          'plymouth fury iii',
           'pontiac catalina',         'amc ambassador dpl',
 ...
 'chrysler lebaron medallion',             'ford granada l',
           'toyota celica gt',          'dodge charger 2.2',
           'chevrolet camaro',            'ford mustang gl',
                  'vw pickup',              'dodge rampage',
                'ford ranger',                 'chevy s-10']
Length: 305, dtype: str

In [129]:
# Since the "car name" is like a identifier kind of column, 
# we are dropping it from the df for the linear model training


df = df.drop(columns = "car name")

df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,18.0,8,307.0,130,3504,12.0,70,1
1,15.0,8,350.0,165,3693,11.5,70,1
2,18.0,8,318.0,150,3436,11.0,70,1
3,16.0,8,304.0,150,3433,12.0,70,1
4,17.0,8,302.0,140,3449,10.5,70,1

In [130]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    str
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
dtypes: float64(3), int64(4), str(1)
memory usage: 25.0 KB

In [131]:
# Here the "horsepower" column is having string datatype .
# Hence we are inspecting that column and then converting it into int values

print(df["horsepower"].unique())

<StringArray>
['130', '165', '150', '140', '198', '220', '215', '225', '190', '170', '160',
  '95',  '97',  '85',  '88',  '46',  '87',  '90', '113', '200', '210', '193',
   '?', '100', '105', '175', '153', '180', '110',  '72',  '86',  '70',  '76',
  '65',  '69',  '60',  '80',  '54', '208', '155', '112',  '92', '145', '137',
 '158', '167',  '94', '107', '230',  '49',  '75',  '91', '122',  '67',  '83',
  '78',  '52',  '61',  '93', '148', '129',  '96',  '71',  '98', '115',  '53',
  '81',  '79', '120', '152', '102', '108',  '68',  '58', '149',  '89',  '63',
  '48',  '66', '139', '103', '125', '133', '138', '135', '142',  '77',  '62',
 '132',  '84',  '64',  '74', '116',  '82']
Length: 94, dtype: str

In [132]:
# We could see '?' on the list

print(df["horsepower"].value_counts()['?'])

6

In [133]:
# Checking if the other column values of the rows having '?' on the "horsepower" is valid or null or '?'
df[df["horsepower"]=='?']

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
32,25.0,4,98.0,?,2046,19.0,71,1
126,21.0,6,200.0,?,2875,17.0,74,1
330,40.9,4,85.0,?,1835,17.3,80,2
336,23.6,4,140.0,?,2905,14.3,80,1
354,34.5,4,100.0,?,2320,15.8,81,2
374,23.0,4,151.0,?,3035,20.5,82,1

### Note

- so there are 6 rows in which the horsepower value is '?'.

- Also ,the other columns of those rows are valid data.

- so removing those rows blindly is not a good approach

- so , lets find the mean of the rest of the values of the colunmns and fill that on these positions of '?' on "hoursepower" column.

In [134]:
# Findinge Mean
mean_of_horsepower = int(df[df["horsepower"]!='?']["horsepower"].astype(int).mean())
print(f"Mean : {mean_of_horsepower}")
df["horsepower"] = df["horsepower"].replace({"?":mean_of_horsepower})
df["horsepower"] = df["horsepower"].astype(int)
df["horsepower"].unique()

Mean : 104

array([130, 165, 150, 140, 198, 220, 215, 225, 190, 170, 160,  95,  97,
        85,  88,  46,  87,  90, 113, 200, 210, 193, 104, 100, 105, 175,
       153, 180, 110,  72,  86,  70,  76,  65,  69,  60,  80,  54, 208,
       155, 112,  92, 145, 137, 158, 167,  94, 107, 230,  49,  75,  91,
       122,  67,  83,  78,  52,  61,  93, 148, 129,  96,  71,  98, 115,
        53,  81,  79, 120, 152, 102, 108,  68,  58, 149,  89,  63,  48,
        66, 139, 103, 125, 133, 138, 135, 142,  77,  62, 132,  84,  64,
        74, 116,  82])

In [135]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    int64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
dtypes: float64(3), int64(5)
memory usage: 25.0 KB

In [136]:
display(df.corr())

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
mpg,1.000000,-0.775396,-0.804203,-0.771543,-0.831741,0.420289,0.579267,0.563450
cylinders,-0.775396,1.000000,0.950721,0.839061,0.896017,-0.505419,-0.348746,-0.562543
displacement,-0.804203,0.950721,1.000000,0.893760,0.932824,-0.543684,-0.370164,-0.609409
horsepower,-0.771543,0.839061,0.893760,1.000000,0.860676,-0.684376,-0.411750,-0.453613
weight,-0.831741,0.896017,0.932824,0.860676,1.000000,-0.417457,-0.306564,-0.581024
acceleration,0.420289,-0.505419,-0.543684,-0.684376,-0.417457,1.000000,0.288137,0.205873
model year,0.579267,-0.348746,-0.370164,-0.411750,-0.306564,0.288137,1.000000,0.180662
origin,0.563450,-0.562543,-0.609409,-0.453613,-0.581024,0.205873,0.180662,1.000000

conclusion from the correlation matrix :
- here "mpg" is the target column
- here , columns like "displacement", "weight", ...are having high correlation with the target feature.
- Hence this data is linear and we can use linear regression to model the relationship between the data.

In [137]:
# x = df[["Temperature (°C)","Ice Cream Sales (units)"]]
x = df.drop(columns = "mpg")
y = df["mpg"]

x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=42)

model_lr = LinearRegression()

model_lr.fit(x_train,y_train)

LinearRegression()

In [138]:

model_lr.intercept_

np.float64(-20.772320899125127)

In [139]:

# Slope

model_lr.coef_

array([-0.1543054 ,  0.01400731, -0.01186018, -0.00677394,  0.0746174 ,
        0.79641357,  1.31372456])

In [140]:
# Predictions

y_train_predicted = model_lr.predict(x_train)

y_test_predicted = model_lr.predict(x_test)

# Regression Evaluation metrics

1. Mean Squared Error (MSE)
2. Root Mean Squared Error (RMSE)
3. Mean Absolute Error (MAE)
4. r^2 score

In [141]:
# 4. r2 score

train_r2_score =r2_score(y_train,y_train_predicted)

test_r2_score= r2_score(y_test,y_test_predicted)


print(train_r2_score, test_r2_score)

0.8139568275400748 0.8475717252829975

In [142]:
# 2. Root Mean Squared Error (RMSE)

train_rmse =root_mean_squared_error(y_train,y_train_predicted)

test_rmse = root_mean_squared_error(y_test,y_test_predicted)


print(train_rmse, test_rmse)

3.4152897574918524 2.8627829569286707

In [143]:
# 3. Mean Absolute Error (MAE)

train_mae =mean_absolute_error(y_train,y_train_predicted)

test_mae = mean_absolute_error(y_test,y_test_predicted)


print(train_mae, test_mae)

2.599262259858809 2.253469317401327

In [144]:
# Error percentage based on the MAE .

# To check if an mae value is high or not we should use it to calculate the error percentage
#  error percentage based on mae equation is : (average(y_train) / mae )* 100

avg_of_y_train = sum(y_train)/len(y_train)

print("Average of Y train: ",avg_of_y_train)

error_percentage_based_on_mae = (avg_of_y_train/train_mae)*100

print("Error percentage based on mae: ",error_percentage_based_on_mae)

Average of Y train:  23.60817610062893
Error percentage based on mae:  908.2644897060644

In [145]:
# 1. Mean Squared Error (MSE)

train_mse = mean_squared_error(y_train,y_train_predicted)

test_mse = mean_squared_error(y_test,y_test_predicted)


print(train_mse, test_mse)

11.664204127628757 8.195526258481262

## Final conclusion:

- r2_score is  high for both train and test splits.
- That means the model understood the internal pattern in the data and will perform well on the unseen future data as well.
- The reason for this that the data is linear data and the linear regression model was able to capture linear data pattern.