In [18]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, root_mean_squared_error,mean_squared_error

In [19]:
df = pd.read_csv("/home/havin-benoy/Desktop/Pyspiders/ml/Datasets/boston.csv")

display(df.head())

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [21]:
display(df.corr())

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
CRIM,1.000000,-0.200469,0.406583,-0.055892,0.420972,-0.219247,0.352734,-0.379670,0.625505,0.582764,0.289946,-0.385064,0.455621,-0.388305
ZN,-0.200469,1.000000,-0.533828,-0.042697,-0.516604,0.311991,-0.569537,0.664408,-0.311948,-0.314563,-0.391679,0.175520,-0.412995,0.360445
INDUS,0.406583,-0.533828,1.000000,0.062938,0.763651,-0.391676,0.644779,-0.708027,0.595129,0.720760,0.383248,-0.356977,0.603800,-0.483725
CHAS,-0.055892,-0.042697,0.062938,1.000000,0.091203,0.091251,0.086518,-0.099176,-0.007368,-0.035587,-0.121515,0.048788,-0.053929,0.175260
NOX,0.420972,-0.516604,0.763651,0.091203,1.000000,-0.302188,0.731470,-0.769230,0.611441,0.668023,0.188933,-0.380051,0.590879,-0.427321
RM,-0.219247,0.311991,-0.391676,0.091251,-0.302188,1.000000,-0.240265,0.205246,-0.209847,-0.292048,-0.355501,0.128069,-0.613808,0.695360
AGE,0.352734,-0.569537,0.644779,0.086518,0.731470,-0.240265,1.000000,-0.747881,0.456022,0.506456,0.261515,-0.273534,0.602339,-0.376955
DIS,-0.379670,0.664408,-0.708027,-0.099176,-0.769230,0.205246,-0.747881,1.000000,-0.494588,-0.534432,-0.232471,0.291512,-0.496996,0.249929
RAD,0.625505,-0.311948,0.595129,-0.007368,0.611441,-0.209847,0.456022,-0.494588,1.000000,0.910228,0.464741,-0.444413,0.488676,-0.381626
TAX,0.582764,-0.314563,0.720760,-0.035587,0.668023,-0.292048,0.506456,-0.534432,0.910228,1.000000,0.460853,-0.441808,0.543993,-0.468536
PTRATIO,0.289946,-0.391679,0.383248,-0.121515,0.188933,-0.355501,0.261515,-0.232471,0.464741,0.460853,1.000000,-0.177383,0.374044,-0.507787
B,-0.385064,0.175520,-0.356977,0.048788,-0.380051,0.128069,-0.273534,0.291512,-0.444413,-0.441808,-0.177383,1.000000,-0.366087,0.333461
LSTAT,0.455621,-0.412995,0.603800,-0.053929,0.590879,-0.613808,0.602339,-0.496996,0.488676,0.543993,0.374044,-0.366087,1.000000,-0.737663
MEDV,-0.388305,0.360445,-0.483725,0.175260,-0.427321,0.695360,-0.376955,0.249929,-0.381626,-0.468536,-0.507787,0.333461,-0.737663,1.000000

Note :
- Here we wanna explore the linear regression in the non linear data .
- so we are only choosing the features that are having low correlation with the output column
- i.e we are choosing only the below columns only as the independent columns:
    1. CHAS
    2. DIS

In [22]:
df = df[["CHAS","DIS","MEDV"]]

display(df.corr())

          CHAS       DIS      MEDV
CHAS  1.000000 -0.099176  0.175260
DIS  -0.099176  1.000000  0.249929
MEDV  0.175260  0.249929  1.000000

conclusion from the correlation matrix:
- Now this dataset only contains the features that are having low correlation.
- hence the data is non linear
- we cannot use linear regression to model the relationship between the features of this dataframe
- But for the experimentation purpose we , are proceeding with the linear regression.

In [23]:

x = df.drop(columns = "MEDV")
y = df["MEDV"]

x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=42)

model_lr = LinearRegression()

model_lr.fit(x_train,y_train)

LinearRegression()

In [24]:

model_lr.intercept_

np.float64(17.847628481648837)

In [25]:

# Slope

model_lr.coef_

array([8.03570305, 1.148073  ])

In [26]:
# Predictions

y_train_predicted = model_lr.predict(x_train)

y_test_predicted = model_lr.predict(x_test)

# Regression Evaluation metrics

1. Mean Squared Error (MSE)
2. Root Mean Squared Error (RMSE)
3. Mean Absolute Error (MAE)
4. r^2 score

In [27]:
# 4. r2 score

train_r2_score =r2_score(y_train,y_train_predicted)

test_r2_score= r2_score(y_test,y_test_predicted)


print(train_r2_score, test_r2_score)

0.10407073108525056 0.07436639937367351

In [28]:
# 2. Root Mean Squared Error (RMSE)

train_rmse =root_mean_squared_error(y_train,y_train_predicted)

test_rmse = root_mean_squared_error(y_test,y_test_predicted)


print(train_rmse, test_rmse)

8.822268709589244 8.238944941813848

In [29]:
# 3. Mean Absolute Error (MAE)

train_mae =mean_absolute_error(y_train,y_train_predicted)

test_mae = mean_absolute_error(y_test,y_test_predicted)


print(train_mae, test_mae)

6.457055018761273 5.906573208911429

In [30]:
# Error percentage based on the MAE .

# To check if an mae value is high or not we should use it to calculate the error percentage
#  error percentage based on mae equation is : (average(y_train) / mae )* 100

avg_of_y_train = sum(y_train)/len(y_train)

print("Average of Y train: ",avg_of_y_train)

error_percentage_based_on_mae = (avg_of_y_train/train_mae)*100

print("Error percentage based on mae: ",error_percentage_based_on_mae)

Average of Y train:  22.796534653465343
Error percentage based on mae:  353.04848088221263

In [31]:
# 1. Mean Squared Error (MSE)

train_mse = mean_squared_error(y_train,y_train_predicted)

test_mse = mean_squared_error(y_test,y_test_predicted)


print(train_mse, test_mse)

77.83242518419745 67.88021375424

## Final conclusion:
- r2_score is very low for both train and test splits of the data.
- That means the model didnt understood the internal pattern or is not capable of understanding the complex non linear pattern in the data.
- Since the test r2 score is low , model will not perform well in the future unseen data as well.
- mae based error percentage is also very high (353 %)