In [74]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, root_mean_squared_error,mean_squared_error

In [75]:
df = pd.read_csv("/home/havin-benoy/Desktop/Pyspiders/ml/Datasets/ENB2012_data.csv")

display(df.head())

     X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28

In [76]:
# Giving appropriate naming as per the official documentation in the kaggle website for this dataset

name_changes = {
"X1":"Relative Compactness",
"X2":"Surface Area",
"X3":"Wall Area",
"X4":"Roof Area",
"X5":"Overall Height",
"X6":"Orientation",
"X7":"Glazing Area",
"X8":"Glazing Area Distribution",
"Y1":"Heating Load",
"Y2":"Cooling Load"
}

df = df.rename(columns= name_changes)

df.head()

,Relative Compactness,Surface Area,Wall Area,Roof Area,Overall Height,Orientation,Glazing Area,Glazing Area Distribution,Heating Load,Cooling Load
0,0.98,514.5,294.0,110.25,7.0,2,0.0,0,15.55,21.33
1,0.98,514.5,294.0,110.25,7.0,3,0.0,0,15.55,21.33
2,0.98,514.5,294.0,110.25,7.0,4,0.0,0,15.55,21.33
3,0.98,514.5,294.0,110.25,7.0,5,0.0,0,15.55,21.33
4,0.90,563.5,318.5,122.50,7.0,2,0.0,0,20.84,28.28

In [77]:
display(df.corr())

,Relative Compactness,Surface Area,Wall Area,Roof Area,Overall Height,Orientation,Glazing Area,Glazing Area Distribution,Heating Load,Cooling Load
Relative Compactness,1.000000e+00,-9.919015e-01,-2.037817e-01,-8.688234e-01,8.277473e-01,4.678592e-17,-2.960552e-15,-7.107006e-16,0.622272,0.634339
Surface Area,-9.919015e-01,1.000000e+00,1.955016e-01,8.807195e-01,-8.581477e-01,-3.459372e-17,3.636925e-15,2.438409e-15,-0.658120,-0.672999
Wall Area,-2.037817e-01,1.955016e-01,1.000000e+00,-2.923165e-01,2.809757e-01,-2.429499e-17,-8.567455e-17,2.067384e-16,0.455671,0.427117
Roof Area,-8.688234e-01,8.807195e-01,-2.923165e-01,1.000000e+00,-9.725122e-01,-5.830058e-17,-1.759011e-15,-1.078071e-15,-0.861828,-0.862547
Overall Height,8.277473e-01,-8.581477e-01,2.809757e-01,-9.725122e-01,1.000000e+00,4.492205e-17,1.489134e-17,-2.920613e-17,0.889431,0.895785
Orientation,4.678592e-17,-3.459372e-17,-2.429499e-17,-5.830058e-17,4.492205e-17,1.000000e+00,-9.406007e-16,-2.549352e-16,-0.002587,0.014290
Glazing Area,-2.960552e-15,3.636925e-15,-8.567455e-17,-1.759011e-15,1.489134e-17,-9.406007e-16,1.000000e+00,2.129642e-01,0.269841,0.207505
Glazing Area Distribution,-7.107006e-16,2.438409e-15,2.067384e-16,-1.078071e-15,-2.920613e-17,-2.549352e-16,2.129642e-01,1.000000e+00,0.087368,0.050525
Heating Load,6.222722e-01,-6.581202e-01,4.556712e-01,-8.618283e-01,8.894307e-01,-2.586534e-03,2.698410e-01,8.736759e-02,1.000000,0.975862
Cooling Load,6.343391e-01,-6.729989e-01,4.271170e-01,-8.625466e-01,8.957852e-01,1.428960e-02,2.075050e-01,5.052512e-02,0.975862,1.000000

Note :
- Here we have two output columns.
- We are choosing the "Cooling Load" as the target column
Also, 
- Here we wanna explore the linear regression in the non linear data .
- so we are only choosing the features that are having low correlation with the output column
- i.e we are choosing only the below columns only as the independent columns:
    1. Orientation
    2. Glazing Area Distribution

In [78]:
df = df[["Orientation","Glazing Area Distribution","Cooling Load"]]

display(df.corr())

,Orientation,Glazing Area Distribution,Cooling Load
Orientation,1.000000e+00,-2.549352e-16,0.014290
Glazing Area Distribution,-2.549352e-16,1.000000e+00,0.050525
Cooling Load,1.428960e-02,5.052512e-02,1.000000

conclusion from the correlation matrix:
- Now this dataset only contains the features that are having low correlation.
- hence the data is non linear
- we cannot use linear regression to model the relationship between the features of this dataframe
- But for the experimentation purpose, we are proceeding with the linear regression.

In [79]:

x = df.drop(columns = "Cooling Load")
y = df["Cooling Load"]

x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=42)

model_lr = LinearRegression()

model_lr.fit(x_train,y_train)

LinearRegression()

In [80]:

model_lr.intercept_

np.float64(23.455504316247332)

In [81]:

# Slope

model_lr.coef_

array([0.07134842, 0.25171795])

In [82]:
# Predictions

y_train_predicted = model_lr.predict(x_train)

y_test_predicted = model_lr.predict(x_test)

# Regression Evaluation metrics

1. Mean Squared Error (MSE)
2. Root Mean Squared Error (RMSE)
3. Mean Absolute Error (MAE)
4. r^2 score

In [83]:
# 4. r2 score

train_r2_score =r2_score(y_train,y_train_predicted)

test_r2_score= r2_score(y_test,y_test_predicted)


print(train_r2_score, test_r2_score)

0.0017760366488499546 -0.0024100625282112986

In [84]:
# 2. Root Mean Squared Error (RMSE)

train_rmse =root_mean_squared_error(y_train,y_train_predicted)

test_rmse = root_mean_squared_error(y_test,y_test_predicted)


print(train_rmse, test_rmse)

9.460433339724492 9.637455400233549

In [85]:
# 3. Mean Absolute Error (MAE)

train_mae =mean_absolute_error(y_train,y_train_predicted)

test_mae = mean_absolute_error(y_test,y_test_predicted)


print(train_mae, test_mae)

8.520985953629312 8.710743401356794

In [86]:
# Error percentage based on the MAE .

# To check if an mae value is high or not we should use it to calculate the error percentage
#  error percentage based on mae equation is : (average(y_train) / mae )* 100

avg_of_y_train = sum(y_train)/len(y_train)

print("Average of Y train: ",avg_of_y_train)

error_percentage_based_on_mae = (avg_of_y_train/train_mae)*100

print("Error percentage based on mae: ",error_percentage_based_on_mae)

Average of Y train:  24.4107654723127
Error percentage based on mae:  286.478179933104

In [87]:
# 1. Mean Squared Error (MSE)

train_mse = mean_squared_error(y_train,y_train_predicted)

test_mse = mean_squared_error(y_test,y_test_predicted)


print(train_mse, test_mse)

89.4997989753707 92.8805465914908

## Final conclusion:
- r2_score is very low for both train and test splits of the data.
- That means the model didnt understood the internal pattern or is not capable of understanding the complex non linear pattern in the data.
- Since the test r2 score is low , model will not perform well in the future unseen data as well.
- mae based error percentage is also very high (286.478179933104 %)